apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-kube-assignment
  labels:
    app: kube-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube-app
  template:
    metadata:
      labels:
        app: kube-app
    spec:
      containers:
      - name: devops-kube-assignment
        image: bhumibha/newassignmentdevops:latest
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
